import assert from "node:assert/strict";
import {whiteWinningPercent,moveReview,meanAccuracy,averageCentipawnLoss,needsConfirmation} from "../static/review-math.js";
const close=(actual,expected)=>assert.ok(Math.abs(actual-expected)<0.00001,`${actual} != ${expected}`);
const cp=value=>({cp:value,mate:null,mateWinner:null});
const mate=(winner,distance=1)=>({cp:null,mate:distance,mateWinner:winner});
close(whiteWinningPercent(cp(0)),50);
close(whiteWinningPercent(cp(100)),59.10258972);
close(whiteWinningPercent(cp(-100)),40.89741028);
assert.equal(moveReview(cp(0),cp(0),"w").accuracy,100);
assert.equal(moveReview(cp(0),cp(100),"w").loss,0);
assert.equal(moveReview(cp(0),cp(100),"b").loss,100);
const equal=moveReview(cp(0),cp(-300),"w"),winning=moveReview(cp(1000),cp(700),"w");
assert.equal(equal.kind,"blunder");assert.equal(winning.loss,300);
assert.ok(winning.accuracy>equal.accuracy+40,'The same material loss matters less in a won position');
close(moveReview(cp(200),cp(-100),"w").accuracy,moveReview(cp(-200),cp(100),"b").accuracy);
assert.equal(whiteWinningPercent(mate("w",0)),100);assert.equal(whiteWinningPercent(mate("b",0)),0);
assert.equal(moveReview(mate("w"),mate("w",10),"w").accuracy,100,'Longer forced mate is still a win');
assert.equal(moveReview(mate("w"),cp(0),"w").loss,null,'Mate must not become artificial centipawn loss');
assert.equal(moveReview(mate("w"),mate("b"),"w").accuracy,0);
assert.equal(moveReview(cp(0),mate("b",0),"b").accuracy,100);
assert.equal(needsConfirmation(cp(0),cp(-300),"w"),true);
assert.equal(needsConfirmation(cp(0),cp(0),"w"),false);
assert.equal(needsConfirmation(mate("w"),mate("b"),"w"),true);
assert.equal(needsConfirmation(mate("w",2),mate("w",5),"w"),false);
assert.equal(meanAccuracy([],"w"),null);
const stable=[{color:"w",accuracy:80,beforeWin:50,afterWin:50},{color:"w",accuracy:100,beforeWin:50,afterWin:50}];
close(meanAccuracy(stable,"w"),89.4444444444);assert.equal(meanAccuracy(stable,"b"),null);
const volatile=[{color:"w",accuracy:80,beforeWin:50,afterWin:70},{color:"b",accuracy:100,beforeWin:70,afterWin:70},{color:"w",accuracy:100,beforeWin:70,afterWin:70}];
close(meanAccuracy(volatile,"w"),84.9206349206,'Critical moves receive more weight');
assert.ok(Number.isFinite(meanAccuracy(volatile,"w",100)),'Partial long games have finite provisional results');
assert.equal(meanAccuracy(stable.map(r=>({...r,accuracy:0})),"w"),0);
assert.equal(meanAccuracy(stable.map(r=>({...r,accuracy:100})),"w"),100);
const losses=[{color:"w",loss:100},{color:"w",loss:300},{color:"w",loss:null},{color:"b",loss:999}];
assert.equal(averageCentipawnLoss(losses,"w"),200);
assert.equal(averageCentipawnLoss([{color:"b",loss:null}],"b"),null);
for(let before=-2000;before<=2000;before+=100)for(const color of ['w','b']){
 const r=moveReview(cp(before),cp(before-200),color);
 assert.ok(r.accuracy>=0&&r.accuracy<=100&&Number.isFinite(r.accuracy));
}
console.log("PASS: win-chance accuracy, weighted/harmonic game score, color symmetry, mate handling, confirmation and ACPL");
